import { Section } from './types';

export const translations = {
  en: {
    appName: "Mahmoud-Elhadry AI Studio",
    nav: {
      imageGenerator: "Image Generation",
      imageEditor: "Image Editor",
      textToSpeech: "Text to Speech",
      imageToText: "Image to Text",
      aiChat: "AI Chat",
      history: "History",
      settings: "Settings",
    },
    imageGenerator: {
      prompt: "Describe the image you want to create...",
      aspectRatio: "Aspect Ratio",
      model: "Model",
      numImages: "Number of Images",
      generate: "Generate Image",
      generating: "Generating...",
      zoom: "Zoom",
      download: "Download",
      save: "Save to History",
      error: "An error occurred while generating the image.",
    },
    imageEditor: {
        uploadTitle: "Upload an Image to Start Editing",
        uploadButton: "Upload from Device",
        dragDrop: "or drag and drop",
        tools: "Editing Tools",
        resize: "Resize",
        crop: "Crop",
        colors: "Colors",
        enhance: "Enhance",
        removeBg: "Remove BG",
        filters: "Filters",
        reset: "Reset",
        save: "Save Image",
        delete: "Delete",
        width: "Width",
        height: "Height",
        brightness: "Brightness",
        contrast: "Contrast",
        saturation: "Saturation",
        temperature: "Temperature",
        apply: "Apply Edit",
        original: "Original",
        cinematic: "Cinematic",
        bw: "B&W",
        blurry: "Blurry",
        highContrast: "High Contrast",
        editPrompt: "Describe the change you want to make...",
        error: "An error occurred while editing the image."
    },
    textToSpeech: {
      enterText: "Enter text to convert to speech...",
      voice: "Voice",
      voiceStyle: "Voice Style (e.g., cheerful, professional)",
      generateAudio: "Generate Audio",
      generating: "Generating...",
      downloadAudio: "Download Audio",
      lastRecording: "Last Generated Audio",
      error: "Failed to generate audio.",
      voices: {
        zephyr: 'Zephyr (Female, Gentle & Airy)',
        puck: 'Puck (Female, Playful & Energetic)',
        kore: 'Kore (Male, Calm & Storyteller)',
        charon: 'Charon (Male, Deep & Authoritative)',
        fenrir: 'Fenrir (Male, Epic & Powerful)',
      }
    },
    imageToText: {
        uploadTitle: "Upload an Image to Extract Text",
        uploadButton: "Upload from Device",
        dragDrop: "or drag and drop",
        convertToText: "Convert to Text",
        converting: "Converting...",
        extractedText: "Extracted Text",
        copy: "Copy",
        downloadTxt: "Download (.txt)",
        translate: "Translate",
        save: "Save to History",
        error: "Failed to extract text from image.",
    },
    aiChat: {
        sendMessage: "Send a message or start talking...",
        listening: "Listening...",
        stop: "Stop",
        start: "Start",
        thinking: "AI is thinking...",
    },
    history: {
        title: "History",
        noItems: "No items saved in history yet.",
        images: "Images",
        audios: "Audios",
        texts: "Texts",
        delete: "Delete",
        reuse: "Reuse Prompt",
    },
    settings: {
        title: "Settings",
        language: "Language",
        theme: "Theme",
        light: "Light",
        dark: "Dark",
    },
  },
  ar: {
    appName: "محمود الحضري ستوديو الذكاء الاصطناعي",
    nav: {
      imageGenerator: "إنشاء الصور",
      imageEditor: "تعديل الصور",
      textToSpeech: "تحويل النص إلى صوت",
      imageToText: "تحويل الصورة إلى نص",
      aiChat: "الدردشة",
      history: "السجل",
      settings: "الإعدادات",
    },
    imageGenerator: {
      prompt: "صف الصورة التي تريد إنشاءها...",
      aspectRatio: "أبعاد الصورة",
      model: "النموذج",
      numImages: "عدد الصور",
      generate: "إنشاء الصورة",
      generating: "جاري الإنشاء...",
      zoom: "تكبير",
      download: "تحميل",
      save: "حفظ في السجل",
      error: "حدث خطأ أثناء إنشاء الصورة.",
    },
    imageEditor: {
        uploadTitle: "ارفع صورة لبدء التعديل",
        uploadButton: "رفع من الجهاز",
        dragDrop: "أو اسحب وأفلت",
        tools: "أدوات التعديل",
        resize: "تغيير الحجم",
        crop: "قص",
        colors: "الألوان",
        enhance: "تحسين الجودة",
        removeBg: "إزالة الخلفية",
        filters: "فلاتر",
        reset: "إعادة تعيين",
        save: "حفظ الصورة",
        delete: "حذف",
        width: "العرض",
        height: "الطول",
        brightness: "السطوع",
        contrast: "التباين",
        saturation: "التشبع",
        temperature: "حرارة اللون",
        apply: "تطبيق التعديل",
        original: "أصلي",
        cinematic: "سينمائي",
        bw: "أبيض وأسود",
        blurry: "ضبابي",
        highContrast: "تباين عالي",
        editPrompt: "صف التغيير الذي تريد إجراءه...",
        error: "حدث خطأ أثناء تعديل الصورة."
    },
    textToSpeech: {
      enterText: "أدخل النص لتحويله إلى كلام...",
      voice: "الصوت",
      voiceStyle: "وصف نمط الصوت (مثال: مبتهج، احترافي)",
      generateAudio: "إنشاء الصوت",
      generating: "جاري الإنشاء...",
      downloadAudio: "تحميل الصوت",
      lastRecording: "آخر تسجيل تم إنشاؤه",
      error: "فشل في إنشاء الصوت.",
      voices: {
        zephyr: 'زفير (أنثى، لطيف وهوائي)',
        puck: 'باك (أنثى، مرح وحيوي)',
        kore: 'كوري (ذكر، هادئ وراوي)',
        charon: 'شارون (ذكر، عميق ورسمي)',
        fenrir: 'فنرير (ذكر، ملحمي وقوي)',
      }
    },
    imageToText: {
        uploadTitle: "ارفع صورة لاستخراج النص منها",
        uploadButton: "رفع من الجهاز",
        dragDrop: "أو اسحب وأفلت",
        convertToText: "تحويل إلى نص",
        converting: "جاري التحويل...",
        extractedText: "النص المستخرج",
        copy: "نسخ",
        downloadTxt: "تحميل (.txt)",
        translate: "ترجمة",
        save: "حفظ في السجل",
        error: "فشل في استخراج النص من الصورة.",
    },
    aiChat: {
        sendMessage: "أرسل رسالة أو ابدأ التحدث...",
        listening: "أستمع...",
        stop: "إيقاف",
        start: "بدء",
        thinking: "الذكاء الاصطناعي يفكر...",
    },
    history: {
        title: "السجل",
        noItems: "لا توجد عناصر محفوظة في السجل بعد.",
        images: "الصور",
        audios: "الصوتيات",
        texts: "النصوص",
        delete: "حذف",
        reuse: "إعادة استخدام الوصف",
    },
    settings: {
        title: "الإعدادات",
        language: "اللغة",
        theme: "المظهر",
        light: "فاتح",
        dark: "داكن",
    },
  },
};

export const SECTIONS: { id: Section; labelKey: keyof typeof translations.en.nav }[] = [
    { id: 'image-generator', labelKey: 'imageGenerator' },
    { id: 'image-editor', labelKey: 'imageEditor' },
    { id: 'text-to-speech', labelKey: 'textToSpeech' },
    { id: 'image-to-text', labelKey: 'imageToText' },
    { id: 'ai-chat', labelKey: 'aiChat' },
    { id: 'history', labelKey: 'history' },
    { id: 'settings', labelKey: 'settings' },
];

export const IMAGE_MODELS = [
    { id: 'imagen-4.0-generate-001', name: 'Imagen 4' },
    { id: 'gemini-2.5-flash-image', name: 'Gemini 2.5 Flash Image (Nano Banana)' },
];

export const ASPECT_RATIOS = ['1:1', '16:9', '9:16', '4:3', '3:4'];

export const ALL_TTS_VOICES: { id: string; nameKey: keyof typeof translations.en.textToSpeech.voices }[] = [
    { id: 'Zephyr', nameKey: 'zephyr' },
    { id: 'Puck', nameKey: 'puck' },
    { id: 'Kore', nameKey: 'kore' },
    { id: 'Charon', nameKey: 'charon' },
    { id: 'Fenrir', nameKey: 'fenrir' },
];
